Update CMakeBuild.yml

diff --git a/.github/workflows/CMakeBuild.yml b/.github/workflows/CMakeBuild.yml
--- a/.github/workflows/CMakeBuild.yml
+++ b/.github/workflows/CMakeBuild.yml
@@ -22,7 +22,20 @@ jobs:
     #      key: ${{ runner.os }}-buildtools-${{ hashFiles('vs_buildtools.exe') }}
     
     - name: Install SFML
-      uses: oprypin/install-sfml@v1
+       run: |
+       set -e
+       mkdir sfml_install
+       # TODO: Maybe investigate why the certificate checks for the SFML sources fail
+       wget https://www.sfml-dev.org/files/SFML-2.6.0-sources.zip --no-check-certificate
+       unzip -q SFML-2.6.0-sources.zip
+       pushd SFML-2.6.0 && mkdir build && cd build && cmake .. && make
+       make DESTDIR=$GITHUB_WORKSPACE/sfml_install install
+       popd
+    - name: Build
+      run: |
+       export SFML_INCLUDE_DIR=$GITHUB_WORKSPACE/sfml_install/usr/local/include
+       export SFML_LIBS_DIR=$GITHUB_WORKSPACE/sfml_install/usr/local/lib
+       cargo build --verbose
 
     #- name: Install Visual Studio 2019 Build Tools
     #  run: |
